### ISSUE TITLE
[Suggestion] Add other wide assets

### ISSUE THREAD

**Issue by rfomin** [NightFright2k19/doom_widehud#1]
Thanks for this collection! Have you seen this thread [[doomworld]](https://www.doomworld.com/forum/topic/121385-widescreen-assets-pack-and-appreciation-thread/)? What do you think about integrating other wide assets from it?

**Comment by NightFright2k19** [comment]
I am aware of it, but at this point, I don't feel like cannibalizing other projects. Besides, their focus seems to be rather on widescreen graphics in general, not just statusbars. Therefore, I am pretty confident both projects can coexist peacefully.
