### ISSUE TITLE
Garbage pixels on the left and right of the hud after screen flashes in GLBoom

### ISSUE THREAD

**Issue by HugeTaffer** [NightFright2k19/doom_widehud#3]
![PRBOOM+ Screenshot 2022 12 18 - 18 54 38 62](https://user-images.githubusercontent.com/78643072/208312179-b9f99c6d-a920-408b-8867-7a1f575eeb4e.png)

This only occurs on the opengl renderer of PRBoom+, the only wad in my collection that isn't affected by this issue is Sunder. I've tried resetting my PRBoom+ settings but with no luck. Any idea what's going on?

**Comment by NightFright2k19** [comment]
Must be an OpenGL issue, then. Can't do anything about it. These statusbars have been converted to the Doom palette with SLADE and work reliably with vanilla ports that use software rendering. 

You are probably better off reporting this in the PrBoom+ Github.
